### ISSUE TITLE
需求：解码UInt8List

### ISSUE THREAD

**Issue by ismlsmile** [lixiangthinker/fast_gbk#2]
希望能直接解码UInt8List类型的参数

**Comment by lixiangthinker** [comment]
没明白需求，  Uint8List 是List<Int> 的实现类，默认是支持的。
////////////
var unit8List = Uint8List.fromList([0xB4, 0xBA]);
  var decoded = gbk.decode(unit8List);
  assert(decoded == "春");
////////////
  var intList = [0xB4, 0xBA];
  decoded = gbk.decode(intList);
  assert(decoded == "春");

**Comment by ismlsmile** [comment]
我重新测试了下，确实是我的测试代码写的有问题，感谢支持！
