### ISSUE TITLE
对GB18030编码支持不完全

### ISSUE THREAD

**Issue by mabDc** [lixiangthinker/fast_gbk#3]
解析GB18030的网页时遇到了编码超出范围的问题，网页地址http://www.jjwxc.net/onebook.php?novelid=3433838&chapterid=1 ，报错信息为”出现异常。FormatException (FormatException: Bad GBK encoding 0xb120)“ ,如下图：
![fast_gbk_error](https://user-images.githubusercontent.com/19526331/84572159-d4002600-adca-11ea-8006-7b973f63c4b4.png)
换用gbk2utf8解码正常，但是速度太慢，严重影响使用。希望fast_gbk可以增加GB18030编码支持。

**Comment by mabDc** [comment]
发现gbkToUtf16Map注释为https://ssl.icu-project.org/repos/icu/data/trunk/charset/source/gb18030/gbkuni30.txt ，看似GB18030，但是字符数只有23940个，而网上说的的GB18030字符数却有70244个。
![gb18030](https://user-images.githubusercontent.com/19526331/84572530-30644500-adcd-11ea-96e8-47cf1e3b23d4.png)
又去看里gbk2utf8里的编码映射，字符数更少，这么看转换流程可能有bug。

**Comment by mabDc** [comment]
测试网页的2进制，含有不在GB18030范围里的0xb120编码。对比gbk2utf8源码，他的tables里把非范围的编码也放进去了，映射到0，所以没报错。fast_gbk添加标志allowMalformed: true直接无视就好了。

**Comment by lixiangthinker** [comment]
感谢建议，需求记下了。后续看看GB18030的问题。

目前如果有不支持的字符，可以在构造的时候使用添加标志的接口，不会报异常；
  //output a �, instead of throw a exception.
  var codec = GbkCodec(allowMalformed: true);
  var decodedMalform = codec.decode([20001]);

**Comment by mabDc** [comment]
是我的问题。解码同一个网页，gbk2utf8没报错，然后fast_gbk报错了，所以误以为是编码转换有问题，看gbk2utf8源码才知道他的映射表里很多位置填的0，所以这个错误无视就好了。
