### ISSUE TITLE
请问有支持null safety的计划嘛

### ISSUE THREAD

**Issue by leedstyh** [lixiangthinker/fast_gbk#4]
RT

**Comment by lixiangthinker** [comment]
https://github.com/lixiangthinker/fast_gbk/pull/5
有提交已经支持，稍后我发布一个版本到pub.dev

**Comment by lixiangthinker** [comment]
https://pub.dev/packages/fast_gbk/versions/1.0.0-rc

1.0.0-rc 版本已经发布

**Comment by leedstyh** [comment]
Thanks @lixiangthinker
